name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'feat'
  - title: 'Improvements'
    labels:
      - 'perf'
      - 'refactor'
  - title: 'Tests'
    labels:
      - 'tests'
      - 'testing'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
      - 'revert'
  - title: '🧰 Maintenance'
    labels:
      - 'docs'
      - 'chore'
      - 'maintenance'
      - 'style'
      - 'build'
      - 'chores'
      - 'ci'
  - title: '📈 Version Bumps'
    labels:
      - 'dependencies'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  # Changes

  $CHANGES

  For more details see the [full list of changes](https://github.com/kinoplan/utils/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION/).
