package io.kinoplan.demo.models

import io.kinoplan.demo.utils.Constants.HOST

case class Message(
  id: Int,
  primary: String,
  secondary: String,
  person: String
)

object Message {
  val default = List(
    Message(
      id = 1,
      primary = "Brunch this week?",
      secondary = "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      person = s"$HOST/static/images/avatar/5.jpg"
    ),
    Message(
      id = 2,
      primary = "Birthday Gift",
      secondary = "Do you have a suggestion for a good present for John on his work " +
        "anniversary. I am really confused & would love your thoughts on it.",
      person = s"$HOST/static/images/avatar/1.jpg"
    ),
    Message(
      id = 3,
      primary = "Recipe to try",
      secondary = "I am try out this new BBQ recipe, I think this might be amazing",
      person = s"$HOST/static/images/avatar/2.jpg"
    ),
    Message(
      id = 4,
      primary = "Yes!",
      secondary = "I have the tickets to the ReactConf for this year.",
      person = s"$HOST/static/images/avatar/3.jpg"
    ),
    Message(
      id = 5,
      primary = "Doctor's Appointment",
      secondary = "My appointment for the doctor was rescheduled for next Saturday.",
      person = s"$HOST/static/images/avatar/4.jpg"
    ),
    Message(
      id = 6,
      primary = "Discussion",
      secondary = "Menus that are generated by the bottom app bar (such as a bottom " +
        "navigation drawer or overflow menu) open as bottom sheets at a higher elevation " +
        "than the bar.",
      person = s"$HOST/static/images/avatar/5.jpg"
    ),
    Message(
      id = 7,
      primary = "Summer BBQ",
      secondary = "Who wants to have a cookout this weekend? I just got some furniture " +
        "for my backyard and would love to fire up the grill.",
      person = s"$HOST/static/images/avatar/1.jpg"
    )
  )
}